[project]
name = "funtecplot"
version = "1.0.4"
description = "funtecplot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy"]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools]
license-files = []

[dependency-groups]
dev = ["pytest>=9.0.3"]
